### ISSUE TITLE
Crash after a long time with Time Warp

### ISSUE THREAD

**Issue by diibify** [qutescoop/qutescoop#107]
I can crash QT with the following procedure:

- Start normal and showing curent data of VATSIM
- Make a "time warp" that I leave for a long time (>30 minutes or so?)
- When I leave the "Time Warp", it does not show any current data for the time being
- Then I press F5 to reload it and QT crashes

I can only reproduce it if I really have "Time Warp" on for a longer time. The problem has also existed for ages (so has not arisen from any recent change). Maybe you can determine something from the log file.

[log.txt](https://github.com/qutescoop/qutescoop/files/8126718/log.txt)

**Comment by Luca0208** [comment]
What do you mean by "Making a time warp"? Do you just go to Plan -> Time warp and set a fixed time and then leave it at that, or are you also using the step forward function?

I'd like to run a bisect, and since testing whether the bug is present takes quite some time any help in closing in on the timeframe where the issue was introduced would be useful. E.g. can you be more specific than "The problem has also existed for ages" or do you know of any versions/time where the issue did not yet exist?

**Comment by diibify** [comment]
The correct expression would probably have been "in the Time Warp".

If I am IN "Time Warp" mode (e.g. selecting a time in the future), stay there for a while without touching anything and then go back to live mode (Unwarp), QT will crash sometimes. The message "whazzupData are older than 30 minutes" still appears in the status line" before the crash. I usually try a quick manual reload with F5 and I think this reload is partly to bug.

And the bug was not "introduced" now in the "current" development. As I said, it already appeared with the old version, which ran for years. So I'll just say since the beginning of QT ;-)

As I said, the crash is not 100% reproducible. But always at the same point. However, as QT has now run on many different operating systems and hardware over the years, I don't think it's a problem that only affects me.

**Comment by jonaseberle** [comment]
I have not seen crashes but I noticed Time Warp sometimes not showing sectors that it should.
Partly related: https://github.com/qutescoop/qutescoop/issues/49

In case of a crash it would be great if we could find the code point. This can be found after the fact by inspecting the "core dump" - in Linux it is a Kernel option and the generated file can be loaded in a debugger afterwards, so `gdb <core dump file>`, then `bt` to get a backtrace where you exactly see where the Kernel shut down the problem. 
On Windows [this seems to be the option to get the core dump file](https://docs.microsoft.com/en-us/windows/client-management/generate-kernel-or-complete-crash-dump#enable-memory-dump-setting)).
Another option is running a self-compiled version from Qt Creator in debug mode - the built-in debugger stops on crash and allows inspecting the last state.

It would be great if we could have reproduction steps with known data as we had for some other issues.
For example:
* Delete all saved whazzups from `./downloaded`
* Use "user network: https://raw.githubusercontent.com/qutescoop/qutescoop/master/tests/fixtures/issue-6/status.json"
* Select "Time Warp" (F8)
* Enable "use downloaded Whazzups"
* ...


https://www.youtube.com/watch?v=umj0gu5nEGs

**Comment by jonaseberle** [comment]
Here's one doing the first update (F5) after returning from TimeWarp:

```
#0  0x00007ffff6cb364a in QObject::disconnect(QObject const*, char const*, QObject const*, char const*) () from /usr/lib/libQt5Core.so.5
#1  0x000055555559c5a9 in Whazzup::processBookings() ()
#2  0x00007ffff6cbec20 in ?? () from /usr/lib/libQt5Core.so.5
#3  0x00007ffff77306b8 in QNetworkReplyHttpImplPrivate::finished (this=0x5555627eefe0)
    at access/qnetworkreplyhttpimpl.cpp:2280
#4  0x00007ffff6cb1bb0 in QObject::event(QEvent*) () from /usr/lib/libQt5Core.so.5
...
```
