### ISSUE TITLE
Crash in `isPointVisible` on Ubuntu 20.04

### ISSUE THREAD

**Issue by jonaseberle** [qutescoop/qutescoop#121]
```
0x00007fffe885b092 in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
(gdb) bt
#0  0x00007fffe885b092 in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#1  0x00007fffe885b68a in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#2  0x00007fffe888dd4f in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#3  0x00007fffe884bcc6 in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#4  0x00007fffe884065c in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#5  0x00007fffe883fa54 in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#6  0x00007fffe879dc29 in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#7  0x00007fffe8939ddf in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#8  0x00007fffe8939f89 in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#9  0x00007fffe8a60880 in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#10 0x00007fffe8a348c5 in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#11 0x00007fffe894ef4d in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#12 0x0000555555640200 in GLWidget::isPointVisible(double, double, int*, int*) const ()
#13 0x0000555555644407 in GLWidget::renderLabelsComplex(QList<MapObject*> const&, QFont const&, double, QColor, QColor) ()
#14 0x0000555555645016 in GLWidget::renderLabels(QList<MapObject*> const&, QFont const&, double, QColor, QColor) ()
#15 0x00005555556452f7 in GLWidget::renderLabels() ()
#16 0x000055555564ab86 in GLWidget::paintGL() ()
#17 0x00007ffff7d23568 in QGLWidget::glDraw() () from QuteScoop-v2.6.0-linux/lib/libQt5OpenGL.so.5
#18 0x000055555563fa01 in GLWidget::handleRotation(QMouseEvent*) ()

```

**Comment by jonaseberle** [comment]
cannot reproduce any more.
