### ISSUE TITLE
backtraces of recent dev versions

### ISSUE THREAD

**Issue by jonaseberle** [qutescoop/qutescoop#263]
Some backtraces of core dumps:

```
Program terminated with signal SIGSEGV, Segmentation fault.

#0  0x0000560458d7948c in Sector::glPolygonHighlighted (this=0xa0) at src/Sector.cpp:163
#1  0x0000560458de9329 in GLWidget::createHoveredControllersLists (this=0x56045a01eed0, controllers=...) at src/GLWidget.cpp:523
#2  0x0000560458dec921 in GLWidget::paintGL (this=0x56045a01eed0) at src/GLWidget.cpp:946
#3  0x00007f8f055badd5 in QGLWidget::glDraw() () from /usr/lib/libQt5OpenGL.so.5
```

```
#0  0x00007fb2a88cd65b in ?? () from /usr/lib/libQt5Core.so.5
#1  0x00007fb2a88dfdf3 in QMutex::lock() () from /usr/lib/libQt5Core.so.5
#2  0x00007fb2a8a8d40f in QCoreApplicationPrivate::lockThreadPostEventList(QObject*) () from /usr/lib/libQt5Core.so.5
#3  0x00007fb2a8a8e592 in QCoreApplication::postEvent(QObject*, QEvent*, int) () from /usr/lib/libQt5Core.so.5
#4  0x0000563b5dc770b5 in Whazzup::processBookings() ()
#5  0x00007fb2a8abeb41 in ?? () from /usr/lib/libQt5Core.so.5
#6  0x00007fb2a9dc91e8 in ?? () from /usr/lib/libQt5Network.so.5
#7  0x00007fb2a8ab1c80 in QObject::event(QEvent*) () from /usr/lib/libQt5Core.so.5
```

**Comment by jonaseberle** [comment]
Both are fixed in the next commit.
